#!/usr/bin/env  bash
#-----------------------------------------------------------------------
# This shell script is to clean the working scatch and the store 
# directory 
#
#  RDS (Hao Feng)
#  Jul 20, 2013
#
#-----------------------------------------------------------------------
function clean_work {
    echo -n " Please specify the working scratch directory, [./work]: "
    read work

    if [[ $work == "" ]]; then	work="$currpath/work"; fi
    if [ ! -d $work ]; then 
	    echo "no work directory found!"
	    exit
    else
	    cd $work
	    rm -f *
    fi
}

#-----------------------------------------------------------------------
function clean_store {
    echo -n " Please specify the store dirctory, [./store]: "
    read store

    if [[ $store == "" ]]; then	store="$currpath/store"; fi
    if [ ! -d $store ]; then 
	    echo "no store directory found!"
	    exit
    fi

    cd $store
    rmfiles -keep POT_ORI DATA_IN

    cd $currpath
}

#-----------------------------------------------------------------------
#--- main function

currpath=`pwd`
clean_work
clean_store
rm -rf build bin lib
