#!/usr/bin/env  bash
#
#--------------------------------------------------------------------------------
# do vibrational e-mol scattering calculations
#
# RDS (Hao Feng)
# Jul 06, 2013
#
# ---
# Usage:
#    total_vib -t N2 -p DSG -basis M2H -nv 15 -ref HF -sym pg 
#
#--------------------------------------------------------------------------------
#--- options

while test "x$1" != "x"; do
    case $1 in
	-t)     shift; tgt=$1      ;;
	-p)     shift; pot=$1      ;;
	-basis) shift; basis=$1    ;;
	-ref)   shift; ref=$1      ;;
	-sym)   shift; sym=$1      ;;
        -nv)    shift; nv=$1       ;;
	*)                         ;;
    esac
    shift
done

#- default values
if [ "$tgt" == ""    ]; then tgt=H2;     fi
if [ "$pot" == ""    ]; then pot=DSG;    fi
if [ "$ref" == ""    ]; then ref=HF;     fi

if [[ "$nv" == ""   && $tgt == N2 ]]; then nv=15;      fi
if [[ "$nv" == ""   && $tgt == H2 ]]; then nv=4;       fi

if [ "$sym" == ""    ]; then 
    SYMM=(sg su pg pu)
else
    SYMM=($sym)
fi

if [ "$basis" == ""  ]; then 
    if [[ $tgt == H2 ]]; then
	BS=(CCD CCT CCQ ACCD ACCT ACCQ M2H M2)
    elif [[ $tgt == N2 ]]; then
 	BS=(CCD CCT CCQ ACCD ACCT ACCQ M2H)
    fi
else
    BS=($basis)
fi

case $tgt in
    H2)
	RE=(0.500 0.800 1.000 1.200 1.400 1.600 1.800 2.000 2.200 2.500 2.600)
	;;
    N2)
# 	RE=(1.600 1.700 1.800 1.850 1.900 1.950 2.000 2.020 2.068 2.100 2.200 2.300 2.400 2.500)
#
#       MO changes and static correlation makes strong when R >= 2.900
 	RE=(1.500 1.600 1.700 1.800 1.850 1.900 1.950 2.000 2.020 2.068 2.100 2.200 2.300 2.400 2.500 2.600 2.700 2.800)
	;;
esac

#---
# vibratioal coupled local potentials and multipole moments
for basis in ${BS[@]}; do
    for R in ${RE[@]}; do
    	./enmv   -t $tgt -basis $basis -R $R 
    	./alam   -t $tgt -basis $basis -R $R -p $pot
    	./vstat  -t $tgt -basis $basis -R $R -p $pot
#    	./vpola  -t $tgt -basis $basis -R $R -p $pot -method vxz

    	./fitpol -t $tgt -basis $basis -R $R -p $pot
    	./vstpol -t $tgt -basis $basis -R $R -p $pot
    	./wlut   -t $tgt -basis $basis -R $R -p $pot
    	./mpmom  -t $tgt -basis $basis -R $R -p $pot
    done

    # for R in ${RE[@]}; do
    # 	./spfd   -t $tgt -basis $basis -R $R -p $pot
    # done

    ./wlam  -t $tgt -basis $basis -R ${RE[@]} -p $pot -nv $nv -cp mpmom 
    ./wlam  -t $tgt -basis $basis -R ${RE[@]} -p $pot -nv $nv -cp pot 
done

#---
# vibrational coupled exchange potential & do Linear-Algebraic scatting equation calculations
for basis in ${BS[@]}; do
    for sym in ${SYMM[@]}; do
	#---
	for R in ${RE[@]}; do
	    ./exker  -t $tgt -basis $basis -R $R -p $pot -sym $sym
	done
	#---
	./wlam  -t $tgt -basis $basis -R ${RE[@]} -p $pot -sym $sym -nv $nv -cp exk
	#---
	./lavib -t $tgt -basis $basis -R ${RE[@]} -p $pot -sym $sym -nv $nv
    done
done
