#!/bin/bash

case $1 in
    H2)
	RE=(0.500 0.800 1.000 1.200 1.400 1.600 1.800 2.000 2.200 2.500 2.600)
	BS=(CCD CCT CCQ ACCD ACCT ACCQ M2H M2)
	;;
    N2)
	RE=(1.600 1.700 1.800 1.850 1.900 1.950 2.000 2.020 2.068 2.100 2.200 2.300 2.400 2.500 2.600 2.700)
 	BS=(CCD CCT CCQ ACCD ACCT ACCQ M2H)
	;;
esac

SYMM=(sg su pg pu)

pot=$2; if [[ $pot == "" ]]; then pot=BTAD; fi

for basis in ${BS[@]}; do
    for R in ${RE[@]}; do
    	./enmv   -t $1 -basis $basis -R $R 
    	./alamn  -t $1 -basis $basis -R $R -p $pot
    	./vstat  -t $1 -basis $basis -R $R -p $pot
#    	./vpola  -t $1 -basis $basis -R $R -p $pot -method vxz

    	./fitpol -t $1 -basis $basis -R $R -p $pot
    	./vstpol -t $1 -basis $basis -R $R -p $pot
    	./wlut   -t $1 -basis $basis -R $R -p $pot
    	./spfd   -t $1 -basis $basis -R $R -p $pot
    	./mpmom  -t $1 -basis $basis -R $R -p $pot
    done
    ./wlam  -t $1 -basis $basis -R ${RE[@]} -p $pot -cp mpmom
    ./wlam  -t $1 -basis $basis -R ${RE[@]} -p $pot -cp pot
done

for basis in ${BS[@]}; do
    for sym in ${SYMM[@]}; do
	for R in ${RE[@]}; do
	    ./exker  -t $1 -basis $basis -R $R -p $pot -sym $sym
	done

	./wlam  -t $1 -basis $basis -R ${RE[@]} -p $pot -cp exk -sym $sym
    done
done

for sym in ${SYMM[@]}; do
    ./lavib  -t $1 -basis $basis -R ${RE[@]} -p $pot -cp exk -sym $sym
done
