#!/usr/bin/env bash
#
#--------------------------------------------------------------------------------
#  reorder the potential file (all the lambdas for a given r first,
#  then all the lamdas for the next r)
#
#  RDS (Hao Feng)
#  Jun 29, 2013
#
# ---
#  Usage:
#    wlut -t N2 -p DSG -basis ACCQ -R 2.02 -ref HF
#
#--------------------------------------------------------------------------------
#--- options
function handle_opt {
    while test "x$1" != "x"; do
	case $1 in
	    -t)     shift; tgt=$1      ;;
	    -p)     shift; pot=$1      ;;
	    -basis) shift; basis=$1    ;;
	    -R)     shift; CRD=$1      ;;
	    -ref)   shift; ref=$1      ;;
	    *)                         ;;
	esac
	shift
    done

#- default values
    if [ "$tgt" == ""    ]; then tgt=H2;     fi
    if [ "$pot" == ""    ]; then pot=DSG;    fi
    if [ "$basis" == ""  ]; then basis=CCD;  fi
    if [ "$CRD" == ""    ]; then CRD=1.400;  fi
    if [ "$ref" == ""    ]; then ref=HF;     fi

#- echo OPTIONS
    echo "$0 -t $tgt -p $pot -basis $basis -R $CRD -ref $ref"
    echo
}

#--------------------------------------------------------------------------------
#--- locations
function set_location {
    work="/Users/fengh/Research/Scatt/bfsca/work"
    storeT="/Users/fengh/Research/Scatt/bfsca/store"
    store="$storeT/wlut/$tgt/$ref/$pot/$basis"
    datain="$storeT/vstpol/$tgt/$ref/$pot/$basis"
}

#--------------------------------------------------------------------------------
#--- cd work directory
#
function cd_work {
    curr=`pwd`
    if [ -d $work ]; then
	rm -f   $work/*
	ln -s   $curr/../bin/wlut.x   $work/.
	cd      $work
    else
	echo "$work does NOT exit!"
	exit
    fi
}

#--------------------------------------------------------------------------------
#--- MAIN FUNCTION
#
handle_opt $@

set_location
cd_work

ln -s $datain/vspR${CRD}.dat  fort.10

$work/wlut.x > $tgt.out

cp   fort.11    $store/sp.R${CRD}
